# Generated by Django 4.2.4 on 2023-12-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='date_of_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
